title: CalcNest
description: Free online calculators for everyday US finance and lifestyle needs.
url: "https://justcalcit.online"
baseurl: ""

markdown: kramdown
permalink: /calcnest/:title/

lang: en
timezone: America/New_York

collections_dir: blog

collections:
  calculators:
    output: true
    permalink: /calcnest/:path/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
